GET http://localhost:3001/
###
POST http://localhost:3001/api/post
Content-Type: application/json

{
    "fruit" : "grapes"
}
###
GET http://localhost:3000/api/names
###
POST http://localhost:3000/api/post
Content-Type: application/json

{
    "name": "Ron",
    "surname": "Weasley"
}
###
