GET http://localhost:3000/api/pets
###
GET http://localhost:3000/api/pets/cat
###
POST http://localhost:3000/api/pets
Content-Type: application/json

{
"name": "Binksas",
"type": "cat",
"age": 16
}
###