###
GET http://localhost:3000/

###
GET http://localhost:3000/api/users

###
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "email": "petunia@email.com",
  "password": "123456",
  "password2": "123456"
}
###

POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "petunia2@email.com",
  "password": "123456"
}
###



GET http://localhost:3000/api/books
###

GET http://localhost:3000/api/authors
###