### SERVICES -------------------------------------------
GET http://localhost:3000/api/services

###
POST http://localhost:3000/api/services
Content-Type: application/json

{
"name": "Platinum",
"price": 149.99,
"description": "Platinum Yearly Subscription"
}
###

DELETE http://localhost:3000/api/services/6261096b19cd311074c67d20
###

GET http://localhost:3000/api/services/6261096b19cd311074c67d20

### USERS ----------------------------------------------
GET http://localhost:3000/api/users

###
GET http://localhost:3000/api/users/asc

###
GET http://localhost:3000/api/users/desc

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
"name": "Ralph",
"surname": "Cunningham",
"email": "rcunninghamg@amazon.co.jp",
"service_id": "6261022ee72b2935ba29c683"
}
