GET http://localhost:3000/api/books
###
POST http://localhost:3000/api/books
Content-Type: application/json

{
"title": "Half-Blood Prince",
"year": 2005,
"rating": 1
}
###
GET http://localhost:3000/api/books/625e631a66ce279f277a5c73
###
GET http://localhost:3000/api/authors
###
POST http://localhost:3000/api/authors
Content-Type: application/json

{
"name": "William Golding",
"country": "United Kingdom",
"bookId": "625e639966ce279f277a5c75"
}
###
GET http://localhost:3000/api/authors/625e71cca7b47314af517d16
###