GET http://localhost:3000/api/users
###
POST http://localhost:3000/api/users
###
POST http://localhost:3000/api/users
Content-Type: application/json

{
"email": "test.com",
"gender": "female",
"hasCar": true,
"age": 50
}
###
GET http://localhost:3000/api/users/hascar
###
GET http://localhost:3000/api/users/males
###
GET http://localhost:3000/api/users/females
###
GET http://localhost:3000/api/users/age/gt/20
###
GET http://localhost:3000/api/users/email/test6@test.com,test3@test.com
###
GET http://localhost:3000/api/users/email/test6@test.com
###