GET http://localhost:3000/api/users
###
POST http://localhost:3000/api/users
###
POST http://localhost:3000/api/users
Content-Type: application/json

{
"email": "test.com",
"gender": "female",
"hasCar": true,
"age": 50
}
###
GET http://localhost:3000/api/users/hascar
###
GET http://localhost:3000/api/users/males
###
GET http://localhost:3000/api/users/females
###
