GET http://localhost:3000/api/users
###
GET http://localhost:3000/api/users/sort-age
###
GET http://localhost:3000/api/users/sort-age/ASC
###
GET http://localhost:3000/api/users/sort-age/DESC
###
GET http://localhost:3000/api/users/students
###
GET http://localhost:3000/api/users/city/Kaunas
###
POST http://localhost:3000/api/users
Content-Type: application/json

{
"name": "Ron",
"age": 80,
"isStudent": false,
"gender": "male",
"city": "Kaunas"
}
###